### PR TITLE
create recipient id in posts table using user_id as FK

### PR DESCRIPTION
**Pull request by j-dav**

### CODE REVIEW

**Comment by Hives** [comment]
[database stream 2) link users to posts again via 'recipient_id' [MEDIUM]](https://trello.com/c/mapturCT/59-database-stream-2-link-users-to-posts-again-via-recipientid-medium)

**Comment by Hives** [comment]
[database stream 2) link users to posts again via 'recipient_id' [MEDIUM]](https://trello.com/c/mapturCT/59-database-stream-2-link-users-to-posts-again-via-recipientid-medium)

**Comment by Hives** [comment]
ok with me

**Comment by arthurashman** [comment]
Looks good

**Pull request merged**
